"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 07:00:53.147911
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('ts', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fake_calendar_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_utc', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_utc', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('appointment_id', sa.String(length=64), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('outbox_messages',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_table('patients',
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_enc', sa.Text(), nullable=True),
    sa.Column('name_enc', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('preferred_language', sa.String(length=2), nullable=False),
    sa.Column('consent_given_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('consent_version', sa.String(length=16), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('last_inbound_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('noshow_count', sa.Integer(), nullable=False),
    sa.Column('late_cancel_count', sa.Integer(), nullable=False),
    sa.Column('anonymised_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_hash')
    )
    op.create_table('processed_messages',
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    op.create_table('session_state',
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('doctor_started_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('doctor_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('delay_until', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('closed_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_clinic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date', 'session', name='uq_session_state')
    )
    op.create_table('appointments',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('start_utc', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_utc', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('visit_reason_short_enc', sa.Text(), nullable=True),
    sa.Column('gcal_event_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('confirmed_by_patient_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('token_no', sa.Integer(), nullable=False),
    sa.Column('token_label', sa.String(length=32), nullable=False),
    sa.Column('is_walk_in', sa.Boolean(), nullable=False),
    sa.Column('queue_status', sa.String(length=20), nullable=False),
    sa.Column('queue_position', sa.Float(), nullable=False),
    sa.Column('priority', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('called_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('consult_started_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('consult_ended_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('skipped_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('displacement_count', sa.Integer(), nullable=False),
    sa.Column('patient_reported_late_minutes', sa.Integer(), nullable=True),
    sa.Column('arrived_hint_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_eta_sent_local', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('needs_staff_decision', sa.String(length=32), nullable=True),
    sa.Column('cancelled_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.String(length=16), nullable=True),
    sa.Column('cancel_reason_code', sa.String(length=32), nullable=True),
    sa.Column('is_late_cancel', sa.Boolean(), nullable=False),
    sa.Column('rescheduled_from_id', sa.Uuid(), nullable=True),
    sa.Column('previous_token_label', sa.String(length=32), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appt_session', 'appointments', ['session_date', 'session'], unique=False)
    op.create_index('ix_appt_start', 'appointments', ['start_utc'], unique=False)
    op.create_index('uq_appt_booked_slot', 'appointments', ['start_utc'], unique=True, postgresql_where=sa.text("status = 'booked' AND is_walk_in = false"), sqlite_where=sa.text("status = 'booked' AND is_walk_in = 0"))
    op.create_index('uq_appt_session_token', 'appointments', ['session_date', 'session', 'token_label'], unique=True, postgresql_where=sa.text("status NOT IN ('cancelled', 'rescheduled')"), sqlite_where=sa.text("status NOT IN ('cancelled', 'rescheduled')"))
    op.create_table('conversations',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('handoff_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('waitlist',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_patient_id'), 'waitlist', ['patient_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('note_for_patient', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_patient_id'), 'follow_ups', ['patient_id'], unique=False)
    op.create_table('queue_events',
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('ts', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_events_appointment_id'), 'queue_events', ['appointment_id'], unique=False)
    op.create_table('slot_offers',
    sa.Column('slot_start_utc', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('source_appointment_id', sa.Uuid(), nullable=True),
    sa.Column('offer_type', sa.String(length=16), nullable=False),
    sa.Column('offered_to_appointment_id', sa.Uuid(), nullable=True),
    sa.Column('offered_to_waitlist_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('cascade_depth', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offered_to_appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['offered_to_waitlist_id'], ['waitlist.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['source_appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offer_slot', 'slot_offers', ['slot_start_utc', 'status'], unique=False)
    op.create_table('reminder_log',
    sa.Column('appointment_id', sa.Uuid(), nullable=True),
    sa.Column('follow_up_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sent_at', app.db.models.UTCDateTime(timezone=True), nullable=True),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', 'kind', name='uq_reminder_appt_kind'),
    sa.UniqueConstraint('follow_up_id', 'kind', name='uq_reminder_fu_kind')
    )
    op.create_index(op.f('ix_reminder_log_wa_message_id'), 'reminder_log', ['wa_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_log_wa_message_id'), table_name='reminder_log')
    op.drop_table('reminder_log')
    op.drop_index('ix_offer_slot', table_name='slot_offers')
    op.drop_table('slot_offers')
    op.drop_index(op.f('ix_queue_events_appointment_id'), table_name='queue_events')
    op.drop_table('queue_events')
    op.drop_index(op.f('ix_follow_ups_patient_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_waitlist_patient_id'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_table('conversations')
    op.drop_index('uq_appt_session_token', table_name='appointments', postgresql_where=sa.text("status NOT IN ('cancelled', 'rescheduled')"), sqlite_where=sa.text("status NOT IN ('cancelled', 'rescheduled')"))
    op.drop_index('uq_appt_booked_slot', table_name='appointments', postgresql_where=sa.text("status = 'booked' AND is_walk_in = false"), sqlite_where=sa.text("status = 'booked' AND is_walk_in = 0"))
    op.drop_index('ix_appt_start', table_name='appointments')
    op.drop_index('ix_appt_session', table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('session_state')
    op.drop_table('processed_messages')
    op.drop_table('patients')
    op.drop_table('outbox_messages')
    op.drop_table('fake_calendar_events')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
